import {
  AArrowUp,
  ActivitySquare,
  Airplay,
  AlarmCheck,
  AlertTriangle,
  BadgeCheck,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Blocks,
  Bot,
  Briefcase,
  CalendarCheck,
  CalendarClock,
  CalendarSync,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  CirclePlay,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  CreditCard,
  Crown,
  Database,
  DoorOpen,
  EyeOff,
  FileText,
  Filter,
  Flame,
  GitMerge,
  GraduationCap,
  Heart,
  Home,
  Hospital,
  Hourglass,
  Inbox,
  Instagram,
  Key,
  Landmark,
  LayoutGrid,
  LayoutList,
  Link,
  Link2,
  Mail,
  MenuSquare,
  MessageCircle,
  MessageSquare,
  MonitorPlay,
  Moon,
  MoveRight,
  Package,
  PartyPopper,
  PhoneCall,
  Play,
  Plug,
  Presentation,
  RefreshCw,
  Repeat,
  Search,
  Share2,
  ShoppingCart,
  Shuffle,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  User,
  UserRound,
  UserX,
  Users,
  Utensils,
  Webcam,
  Workflow,
  Wrench,
  XCircle,
  Zap
} from 'lucide-react'
import type { LucideProps } from 'lucide-react'
import type { ComponentType } from 'react'

/**
 * Icons the public site renders, imported by name so the bundler keeps only these
 * (tree-shaking). `getIcon` from the IconPicker pulls in the ENTIRE lucide set (~500 KB,
 * 136 KB gzipped on every page), which is only needed by the admin picker.
 *
 * Any icon an editor picks that is not listed here still renders: <Icon> falls back to
 * <LazyIcon>, which loads just that one icon on demand. Add frequently used names here
 * to keep them in the main bundle.
 */
export const PUBLIC_ICONS: Record<string, ComponentType<LucideProps>> = {
  'a-arrow-up': AArrowUp,
  'activity-square': ActivitySquare,
  'airplay': Airplay,
  'alarm-check': AlarmCheck,
  'alert-triangle': AlertTriangle,
  'badge-check': BadgeCheck,
  'banknote': Banknote,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'bell-ring': BellRing,
  'blocks': Blocks,
  'bot': Bot,
  'briefcase': Briefcase,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-sync': CalendarSync,
  'check': Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-play': CirclePlay,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'copy': Copy,
  'credit-card': CreditCard,
  'crown': Crown,
  'database': Database,
  'door-open': DoorOpen,
  'eye-off': EyeOff,
  'file-text': FileText,
  'filter': Filter,
  'flame': Flame,
  'git-merge': GitMerge,
  'graduation-cap': GraduationCap,
  'heart': Heart,
  'home': Home,
  'hospital': Hospital,
  'hourglass': Hourglass,
  'inbox': Inbox,
  'instagram': Instagram,
  'key': Key,
  'landmark': Landmark,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'link': Link,
  'link-2': Link2,
  'mail': Mail,
  'menu-square': MenuSquare,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'monitor-play': MonitorPlay,
  'moon': Moon,
  'move-right': MoveRight,
  'package': Package,
  'party-popper': PartyPopper,
  'phone-call': PhoneCall,
  'play': Play,
  'plug': Plug,
  'presentation': Presentation,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'search': Search,
  'share-2': Share2,
  'shopping-cart': ShoppingCart,
  'shuffle': Shuffle,
  'sparkles': Sparkles,
  'star': Star,
  'stethoscope': Stethoscope,
  'tag': Tag,
  'target': Target,
  'timer': Timer,
  'trash-2': Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'user': User,
  'user-round': UserRound,
  'user-x': UserX,
  'users': Users,
  'utensils': Utensils,
  'webcam': Webcam,
  'workflow': Workflow,
  'wrench': Wrench,
  'x-circle': XCircle,
  'zap': Zap
}
