/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    categories: Category;
    authors: Author;
    faqs: Faq;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title when empty. Localized per-locale — used in /[lang]/blog/[slug].
   */
  slug: string;
  category?: (number | null) | Category;
  author?: (number | null) | Author;
  /**
   * Short dek shown on cards and the post header.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Article body. Insert Callout and Inline CTA Banner blocks anywhere.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Promote to the full-bleed featured slot on the blog index.
   */
  featured?: boolean | null;
  /**
   * Auto-computed from content (minutes).
   */
  readTime?: number | null;
  publishedAt?: string | null;
  /**
   * Manual "Keep reading" cards on the single post (display limited to 3).
   */
  relatedPosts?: (number | Post)[] | null;
  /**
   * Advanced: a raw JSON-LD object shallow-merged over this page’s auto-generated schema. Override wins on conflicting keys and arrays are REPLACED, not extended. Policy: the override MUST match the visible page content — mismatched or fake markup (ratings, reviews, searchboxes) triggers a Google manual action. aggregateRating, review, reviews, potentialAction and SearchAction are rejected on save at any depth. Must be a single object including an "@type".
   */
  jsonLdOverride?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from title when left empty. Localized per-locale — used in /[lang]/blog/category/[slug].
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Auto-generated from name when left empty. Used in /[lang]/blog/author/[slug].
   */
  slug: string;
  /**
   * Job title / department shown on the author hero (e.g. "Head of Growth").
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  socials?: {
    linkedin?: string | null;
    x?: string | null;
    website?: string | null;
  };
  /**
   * Topic tags shown in the author sidebar (e.g. "AI Automation").
   */
  expertise?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional vanity stats. Article count is computed at read time in Phase 9.
   */
  stats?: {
    /**
     * Total reads (manual/analytics).
     */
    reads?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Optional caption shown under figures in article content.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from title when empty. Localized per-locale — resolves against the [...slug] catch-all.
   */
  slug: string;
  /**
   * Block-based page layout. The home page is built from these 8 section blocks; arbitrary pages can mix any subset.
   */
  layout?:
    | (
        | HeroBlock
        | LogosBlock
        | ProblemBlock
        | BenefitsBlock
        | TestimonialsBlock
        | PricingBlock
        | FaqBlock
        | CtaBlock
        | HeroCenteredBlock
        | HeroSplitBlock
        | HeroDashboardBlock
        | HeroBoldBlock
        | FeatureGridBlock
        | FeatureZigzagBlock
        | FeatureAccordionBlock
        | StepsBlock
        | TimelineBlock
        | TabsBlock
        | MetricsBlock
        | BigQuoteBlock
        | MiniPricingBlock
        | StrategyFormBlock
        | StickyCtaBlock
        | BonusBannerBlock
        | IntegrationsBlock
        | ComparisonTableBlock
      )[]
    | null;
  /**
   * Optional long-form rich text for simple pages. Block-based pages use the Layout field above instead.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  /**
   * Advanced: a raw JSON-LD object shallow-merged over this page’s auto-generated schema. Override wins on conflicting keys and arrays are REPLACED, not extended. Policy: the override MUST match the visible page content — mismatched or fake markup (ratings, reviews, searchboxes) triggers a Google manual action. aggregateRating, review, reviews, potentialAction and SearchAction are rejected on save at any depth. Must be a single object including an "@type".
   */
  jsonLdOverride?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Eyebrow / pill above the headline.
   */
  badge?: string | null;
  title: string;
  description?: string | null;
  ctaPrimaryLabel?: string | null;
  /**
   * Primary CTA destination (e.g. #pricing).
   */
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  /**
   * Secondary CTA destination. External links (https://wa.me/...) render a chat icon and open in a new tab; internal links render a calendar icon.
   */
  ctaSecondaryHref?: string | null;
  /**
   * Optional logo shown above the headline.
   */
  logo?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  heading: string;
  logos?:
    | {
        name: string;
        /**
         * Logo image URL.
         */
        src: string;
        /**
         * Legacy logo (renders with the grayscale screen treatment).
         */
        old?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Small uppercase label above the country chips.
   */
  globalOperations?: string | null;
  countries?:
    | {
        name: string;
        /**
         * ISO 2-letter country code (drives the flag image).
         */
        code: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemBlock".
 */
export interface ProblemBlock {
  heading: string;
  /**
   * Green pill text under the heading.
   */
  subtitle?: string | null;
  items?:
    | {
        title: string;
        description: string;
        /**
         * Card icon.
         */
        icon?: ('TrendingDown' | 'Clock' | 'Layers' | 'Bot' | 'Settings' | 'Activity') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'problem';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  heading: string;
  subtitle?: string | null;
  items?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading: string;
  subtitle?: string | null;
  items?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  heading: string;
  subtitle?: string | null;
  plans?:
    | {
        /**
         * Drives the per-tier styling (engine = highlighted center card).
         */
        planId: 'foundation' | 'engine' | 'growth';
        name: string;
        /**
         * e.g. $199
         */
        price: string;
        /**
         * e.g. " / month" (falls back to i18n).
         */
        period?: string | null;
        description?: string | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        highlighted?: boolean | null;
        /**
         * Optional badge above the card (engine tier).
         */
        bonus?: string | null;
        ctaLabel: string;
        ctaHref?: string | null;
        /**
         * Optional fine print under the features.
         */
        subText?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: string;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Green pill badge (e.g. "$2,000 BONUS INCLUDED").
   */
  badge?: string | null;
  heading: string;
  body?: string | null;
  /**
   * Emphasised goal line (white text).
   */
  goal?: string | null;
  /**
   * Green safety / disclaimer line.
   */
  safety?: string | null;
  /**
   * Uppercase footnote (e.g. "Cancel anytime").
   */
  cancelAnytime?: string | null;
  /**
   * Optional CTA button label. Leave empty to hide the button.
   */
  buttonLabel?: string | null;
  buttonHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCenteredBlock".
 */
export interface HeroCenteredBlock {
  /**
   * Lucide icon name for the eyebrow pill (e.g. calendar-check).
   */
  pillIcon?: string | null;
  pillText: string;
  /**
   * Headline text before the accented phrase.
   */
  titleStart: string;
  /**
   * Accented phrase (rendered in the brand or green color).
   */
  titleAccent?: string | null;
  /**
   * Headline text after the accented phrase.
   */
  titleEnd?: string | null;
  accentColor?: ('brand' | 'green') | null;
  subtitle?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  /**
   * Optional lucide icon name for the secondary CTA.
   */
  ctaSecondaryIcon?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  /**
   * Small checkmark items under the CTAs (centered/split heroes).
   */
  micro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroCentered';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock".
 */
export interface HeroSplitBlock {
  /**
   * Lucide icon name for the eyebrow pill (e.g. calendar-check).
   */
  pillIcon?: string | null;
  pillText: string;
  /**
   * Headline text before the accented phrase.
   */
  titleStart: string;
  /**
   * Accented phrase (rendered in the brand or green color).
   */
  titleAccent?: string | null;
  /**
   * Headline text after the accented phrase.
   */
  titleEnd?: string | null;
  accentColor?: ('brand' | 'green') | null;
  subtitle?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  /**
   * Optional lucide icon name for the secondary CTA.
   */
  ctaSecondaryIcon?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  /**
   * Small checkmark items under the CTAs (centered/split heroes).
   */
  micro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Placeholder label shown when no image is set.
   */
  placeholder?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroDashboardBlock".
 */
export interface HeroDashboardBlock {
  /**
   * Lucide icon name for the eyebrow pill (e.g. calendar-check).
   */
  pillIcon?: string | null;
  pillText: string;
  /**
   * Headline text before the accented phrase.
   */
  titleStart: string;
  /**
   * Accented phrase (rendered in the brand or green color).
   */
  titleAccent?: string | null;
  /**
   * Headline text after the accented phrase.
   */
  titleEnd?: string | null;
  accentColor?: ('brand' | 'green') | null;
  subtitle?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  /**
   * Optional lucide icon name for the secondary CTA.
   */
  ctaSecondaryIcon?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  /**
   * Small checkmark items under the CTAs (centered/split heroes).
   */
  micro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Placeholder label shown when no mockup image is set.
   */
  placeholder?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroDashboard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBoldBlock".
 */
export interface HeroBoldBlock {
  /**
   * Lucide icon name for the eyebrow pill (e.g. calendar-check).
   */
  pillIcon?: string | null;
  pillText: string;
  /**
   * Headline text before the accented phrase.
   */
  titleStart: string;
  /**
   * Accented phrase (rendered in the brand or green color).
   */
  titleAccent?: string | null;
  /**
   * Headline text after the accented phrase.
   */
  titleEnd?: string | null;
  accentColor?: ('brand' | 'green') | null;
  subtitle?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  /**
   * Optional lucide icon name for the secondary CTA.
   */
  ctaSecondaryIcon?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  /**
   * Small checkmark items under the CTAs (centered/split heroes).
   */
  micro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cards?:
    | {
        /**
         * Lucide icon name.
         */
        icon?: string | null;
        big: string;
        label: string;
        /**
         * Render the icon in the green accent.
         */
        green?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBold';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  eyebrow?: string | null;
  heading: string;
  subtitle?: string | null;
  /**
   * Use the left-aligned two-column intro header (Bold template).
   */
  splitIntro?: boolean | null;
  cards?:
    | {
        /**
         * Lucide icon name.
         */
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureZigzagBlock".
 */
export interface FeatureZigzagBlock {
  eyebrow?: string | null;
  heading?: string | null;
  rows?:
    | {
        /**
         * Kicker label, e.g. "01" or "The problem".
         */
        num?: string | null;
        title: string;
        description: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        placeholder?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureZigzag';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordionBlock".
 */
export interface FeatureAccordionBlock {
  eyebrow?: string | null;
  heading: string;
  image?: (number | null) | Media;
  placeholder?: string | null;
  items?:
    | {
        /**
         * Lucide icon name.
         */
        icon?: string | null;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        /**
         * Lucide icon name for the dot.
         */
        icon?: string | null;
        /**
         * Small uppercase phase tag.
         */
        tag?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock".
 */
export interface TabsBlock {
  eyebrow?: string | null;
  heading: string;
  tabs?:
    | {
        /**
         * Lucide icon name for the tab button.
         */
        icon?: string | null;
        label: string;
        title: string;
        description: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        placeholder?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock".
 */
export interface MetricsBlock {
  /**
   * Add the periwinkle glow band above the metrics.
   */
  glowTop?: boolean | null;
  items?:
    | {
        value: string;
        label: string;
        /**
         * Render the value in the green accent.
         */
        green?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'metrics';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BigQuoteBlock".
 */
export interface BigQuoteBlock {
  /**
   * Add the periwinkle glow band above the quote.
   */
  glowTop?: boolean | null;
  quote: string;
  authorName: string;
  authorRole?: string | null;
  avatar?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bigQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiniPricingBlock".
 */
export interface MiniPricingBlock {
  eyebrow?: string | null;
  heading?: string | null;
  subtitle?: string | null;
  /**
   * Show only the featured plan (standalone .pricing-single).
   */
  single?: boolean | null;
  plans?:
    | {
        name: string;
        sub?: string | null;
        price: string;
        period?: string | null;
        /**
         * Highlight this plan (periwinkle border + scale).
         */
        featured?: boolean | null;
        /**
         * Green pill above a featured plan (e.g. "$2,000 Bonus Included").
         */
        bonusTag?: string | null;
        features?:
          | {
              text: string;
              /**
               * Emphasize (white/bold + green check) — e.g. "FREE $2,000 Setup".
               */
              hot?: boolean | null;
              id?: string | null;
            }[]
          | null;
        ctaLabel: string;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'miniPricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StrategyFormBlock".
 */
export interface StrategyFormBlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Form field labels and placeholders (seed per-locale).
   */
  labels?: {
    name?: string | null;
    namePlaceholder?: string | null;
    company?: string | null;
    companyPlaceholder?: string | null;
    email?: string | null;
    emailPlaceholder?: string | null;
    leads?: string | null;
    submit?: string | null;
    fine?: string | null;
    success?: string | null;
  };
  leadOptions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'strategyForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StickyCtaBlock".
 */
export interface StickyCtaBlock {
  title: string;
  /**
   * Green secondary line (e.g. bonus).
   */
  subtitle?: string | null;
  ctaLabel: string;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stickyCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BonusBannerBlock".
 */
export interface BonusBannerBlock {
  /**
   * Green pill label (e.g. "$2,000 Setup Bonus Included").
   */
  pillText?: string | null;
  heading: string;
  body?: string | null;
  ctaPrimaryLabel?: string | null;
  ctaPrimaryHref?: string | null;
  ctaSecondaryLabel?: string | null;
  ctaSecondaryHref?: string | null;
  fine?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bonusBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsBlock".
 */
export interface IntegrationsBlock {
  eyebrow?: string | null;
  heading: string;
  subtitle?: string | null;
  items?:
    | {
        name: string;
        description: string;
        logo?: (number | null) | Media;
        /**
         * Optional link to the integration doc page.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'integrations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock".
 */
export interface ComparisonTableBlock {
  eyebrow?: string | null;
  heading: string;
  subtitle?: string | null;
  /**
   * Comparison column headers (the row-label column is implicit).
   */
  columns?:
    | {
        label: string;
        /**
         * Render this whole column in the brand/green accent (e.g. the Apturio column).
         */
        highlight?: boolean | null;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        label: string;
        /**
         * One value per column, in the same order as the columns above.
         */
        values?:
          | {
              text: string;
              /**
               * Render this cell in the green accent (e.g. the winning value).
               */
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparisonTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Answer body. Feeds the FAQPage JSON-LD (SCHEMA-03) and the homepage FAQ.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Display order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  featured?: T;
  readTime?: T;
  publishedAt?: T;
  relatedPosts?: T;
  jsonLdOverride?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        problem?: T | ProblemBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        heroCentered?: T | HeroCenteredBlockSelect<T>;
        heroSplit?: T | HeroSplitBlockSelect<T>;
        heroDashboard?: T | HeroDashboardBlockSelect<T>;
        heroBold?: T | HeroBoldBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        featureZigzag?: T | FeatureZigzagBlockSelect<T>;
        featureAccordion?: T | FeatureAccordionBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        tabs?: T | TabsBlockSelect<T>;
        metrics?: T | MetricsBlockSelect<T>;
        bigQuote?: T | BigQuoteBlockSelect<T>;
        miniPricing?: T | MiniPricingBlockSelect<T>;
        strategyForm?: T | StrategyFormBlockSelect<T>;
        stickyCta?: T | StickyCtaBlockSelect<T>;
        bonusBanner?: T | BonusBannerBlockSelect<T>;
        integrations?: T | IntegrationsBlockSelect<T>;
        comparisonTable?: T | ComparisonTableBlockSelect<T>;
      };
  content?: T;
  publishedAt?: T;
  jsonLdOverride?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  description?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  logo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        name?: T;
        src?: T;
        old?: T;
        id?: T;
      };
  globalOperations?: T;
  countries?:
    | T
    | {
        name?: T;
        code?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProblemBlock_select".
 */
export interface ProblemBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  items?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  plans?:
    | T
    | {
        planId?: T;
        name?: T;
        price?: T;
        period?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        highlighted?: T;
        bonus?: T;
        ctaLabel?: T;
        ctaHref?: T;
        subText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  badge?: T;
  heading?: T;
  body?: T;
  goal?: T;
  safety?: T;
  cancelAnytime?: T;
  buttonLabel?: T;
  buttonHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroCenteredBlock_select".
 */
export interface HeroCenteredBlockSelect<T extends boolean = true> {
  pillIcon?: T;
  pillText?: T;
  titleStart?: T;
  titleAccent?: T;
  titleEnd?: T;
  accentColor?: T;
  subtitle?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryIcon?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  micro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSplitBlock_select".
 */
export interface HeroSplitBlockSelect<T extends boolean = true> {
  pillIcon?: T;
  pillText?: T;
  titleStart?: T;
  titleAccent?: T;
  titleEnd?: T;
  accentColor?: T;
  subtitle?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryIcon?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  micro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  placeholder?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroDashboardBlock_select".
 */
export interface HeroDashboardBlockSelect<T extends boolean = true> {
  pillIcon?: T;
  pillText?: T;
  titleStart?: T;
  titleAccent?: T;
  titleEnd?: T;
  accentColor?: T;
  subtitle?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryIcon?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  micro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  placeholder?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBoldBlock_select".
 */
export interface HeroBoldBlockSelect<T extends boolean = true> {
  pillIcon?: T;
  pillText?: T;
  titleStart?: T;
  titleAccent?: T;
  titleEnd?: T;
  accentColor?: T;
  subtitle?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryIcon?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  micro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cards?:
    | T
    | {
        icon?: T;
        big?: T;
        label?: T;
        green?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  splitIntro?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureZigzagBlock_select".
 */
export interface FeatureZigzagBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  rows?:
    | T
    | {
        num?: T;
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        placeholder?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureAccordionBlock_select".
 */
export interface FeatureAccordionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  image?: T;
  placeholder?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        tag?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlock_select".
 */
export interface TabsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  tabs?:
    | T
    | {
        icon?: T;
        label?: T;
        title?: T;
        description?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        placeholder?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetricsBlock_select".
 */
export interface MetricsBlockSelect<T extends boolean = true> {
  glowTop?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        green?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BigQuoteBlock_select".
 */
export interface BigQuoteBlockSelect<T extends boolean = true> {
  glowTop?: T;
  quote?: T;
  authorName?: T;
  authorRole?: T;
  avatar?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MiniPricingBlock_select".
 */
export interface MiniPricingBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  single?: T;
  plans?:
    | T
    | {
        name?: T;
        sub?: T;
        price?: T;
        period?: T;
        featured?: T;
        bonusTag?: T;
        features?:
          | T
          | {
              text?: T;
              hot?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StrategyFormBlock_select".
 */
export interface StrategyFormBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  labels?:
    | T
    | {
        name?: T;
        namePlaceholder?: T;
        company?: T;
        companyPlaceholder?: T;
        email?: T;
        emailPlaceholder?: T;
        leads?: T;
        submit?: T;
        fine?: T;
        success?: T;
      };
  leadOptions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StickyCtaBlock_select".
 */
export interface StickyCtaBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BonusBannerBlock_select".
 */
export interface BonusBannerBlockSelect<T extends boolean = true> {
  pillText?: T;
  heading?: T;
  body?: T;
  ctaPrimaryLabel?: T;
  ctaPrimaryHref?: T;
  ctaSecondaryLabel?: T;
  ctaSecondaryHref?: T;
  fine?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntegrationsBlock_select".
 */
export interface IntegrationsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  items?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonTableBlock_select".
 */
export interface ComparisonTableBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtitle?: T;
  columns?:
    | T
    | {
        label?: T;
        highlight?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        label?: T;
        values?:
          | T
          | {
              text?: T;
              highlight?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  socials?:
    | T
    | {
        linkedin?: T;
        x?: T;
        website?: T;
      };
  expertise?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        reads?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  /**
   * Visual style of the callout box.
   */
  variant: 'keyTakeaway' | 'info' | 'success' | 'warning';
  /**
   * Optional label shown above the body (e.g. "Key Takeaway").
   */
  heading?: string | null;
  /**
   * Callout body. Keep it short — one or two sentences.
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InlineCTABannerBlock".
 */
export interface InlineCTABannerBlock {
  /**
   * Small pill label above the heading (e.g. "Limited offer").
   */
  label?: string | null;
  heading: string;
  body?: string | null;
  buttonLabel: string;
  /**
   * Destination URL or anchor (e.g. /en/strategy-call or #cta).
   */
  href: string;
  /**
   * Use the dark banner surface (recommended inside the white paper).
   */
  dark?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inlineCTABanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}